@host=https://localhost:7127/


//Valid Ticket Request
POST {{host}}ticket/purchase
Content-Type: application/json

{
    "drawId":6,
    "customerId":1,
    "numberoftickets":5,
    "timestamp":"2025-04-02"
}

// Tickets Unavailable Request
POST {{host}}ticket/purchase
Content-Type: application/json

{
    "drawId":6,
    "customerId":1,
    "numberoftickets":6,
    "timestamp":"2025-04-02"
}